// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_chatwindow.cpp"
#include "XLQVKIHBGC/moc_loginwindow.cpp"
#include "IFHPYZAWOD/moc_mainwindow.cpp"
#include "LQ5S74IWJL/moc_registerdialog.cpp"
#include "3G5O7Q7RTY/moc_shoppingcart.cpp"
